dist: trusty
sudo: false
language: ruby
rvm:
  - 2.4
  - 2.3
  - 2.2
  - jruby-9.1.12.0
env:
  matrix:
    - SLIM_VERSION="~> 3.0"
    - SLIM_VERSION="~> 2.1"
  global:
    secure: "JDKKk1i6kK/kbr+JTsnwkn2wbH+mUbWCcO8QBYzR59RK8nw27994r3JHkIA/uOGSe9XO7DRqXrlDoW9rsYJ2BY7+C2IOa6j7Hr14TaFd8kuL1+Z4f0oKKCqaFSTCAQEfNN+3W3Uq/QMpmKCU6chefjm1h7ojGOHK1QvXYRcqhYKfcgS5WJI5C40JIzNFBf9f2uvF1b73vFTWY8UoDMIFMgtfC8hvO8psE6sfypSrfgG51XwyAVMtmqVB9f8VP7lWTEp+h9IK5KcKbHr9ESC64phsMNmkc1+GtzxtGYPP+2mK3qCXx7FsZHH/o8TZdxQXiyXs3QCaT/r4KNbqP//xYgZSHcZjeHTAVc5xqdWhKmhGP8mb6IQidCJtY9RJxxFi//wr5sEuY1WIa1OdRO8jSNwyJzwyWGPx2iY1BYpffMFfW8lGdn7iVKf+rbsVT+NNf9tRA5kDz0aSskYhsfCi1qVbiVIXD2FzNAZR8pD0co0asGZvoc4yoIvAQXFn1Q1U6kvBlYC/R/9J0l+546I4rTZmzgzVYdfPSuwAPjOSxz8bBVlrqQtTHIkazwc/WN1viptC/w3JDLrHlrocqhX8iIaUU3VPc6Dlby4SC6v1QHkcohGDe1jQ2tjyzA520H0yi3Hqg/7F0uM5GG6swjbnazceekd0/VXKS9H9IDDsGro="  # CODACY_PROJECT_TOKEN
script:
  - bundle exec rake spec
  - bundle exec rake rubocop
deploy:
  provider: rubygems
  api_key:
    secure: "qgw+KlchjXRpG+8DnF0O8Z2YSB6wE07Vo/MHCUQ8j/yZB1mNk/81c+og21t2dEDLCJ6XUHRYaLEwaeoeLp4Yz4VhDPpRufDAe97L4vX3zGvz6Uqlhbxu7cCZvfjyw4BlpFWo+JCE7vxBEUnV4ak9mMKA52MvmDsf2iH6PuAIJ4iQC729hbM/HtCmPEEP7qI7oag2fMGmaLm6hQ5HU6k5U8qYjnq+XUuXCxFOXgHF67vDS53bA1NPrP2aN7cFGTmb3NRJ7MZ+kgNJnwjtiHNbPxvnXeK3D90cqcTPPb49Rc+vdvFDFWANHbKeVZfqMSu4ObC2NSJbLxSfIPgnvIhbcvGEUL46Jw4VqqUk+Gzn52UgGugM5iQFgrkv53vX7MB6zA1odCQIsMBk6dW2fcRigYDOzfIRMMvzQrSdglr4JISvc0Tet80v6QoIfuWYh88TLyH54PZNoKXwAozoL7JeGyBRu3/24SBRlQuhZbh3I0uUWULKVhcr7ytH9XnfTyu6NV90Jr6VwWgEIZC7Oh7mN4C1o8KlTodWH+pLQU/85dLYang59G2kKrd4ManSlVct/GMzpEXcxqv2R41+BDTc+vwTDzJ1JQdJUKtUReQueqCj9pLIxCwx+klx2nsODwqBU7oNXZsGMoGH5Oi0QHir44+Kd35cSss393JI/H6nvEY="
  on:
    tags: true
    condition: ${TRAVIS_JOB_NUMBER#*.} = 1
